name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "abhishekc2q" --password-stdin
        docker build -t abhishekc2q/jet-rul .
        docker push abhishekc2q/jet-rul:latest
